### ISSUE TITLE
Issue: generating new ROI name when propagating the contours to the new image set

### ISSUE THREAD

**Issue by pftsai1112** [NewYorkProtonCenter/raystation-scripts#3]
When copying the region-of-interests(ROIs) over to new images, it currently creates new ROI. To keep the workspace clean, when propagating the contours to the new images, keep original contour name.
The only exception is the contours in the target contour type. suggest rigidly copy over the original target contour names (e.g. CTV), and deformably copy over with original contour name_deform.  (e.g. CTV_deform)

**Comment by mivermeu** [comment]
If I understand the discussion correctly, it seems that this is an issue related to importing the patient's plan into Raystation, which is currently not governed by the AutoQACT script.

New target ROIs are currently created with a unique name every time, which creates a lot of ROIs. I'll look into this.
